// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa5vp7krgOX7bdP8r-rFqfjniBQ2opGHs',
    appId: '1:705177585451:web:a3a37ad4fcc9b9c379276e',
    messagingSenderId: '705177585451',
    projectId: 'uber-clone-adam',
    authDomain: 'uber-clone-adam.firebaseapp.com',
    storageBucket: 'uber-clone-adam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAieY61RcaMn8EOlujSWhvUPWTHBs6evJc',
    appId: '1:705177585451:android:374a4f502de3618979276e',
    messagingSenderId: '705177585451',
    projectId: 'uber-clone-adam',
    storageBucket: 'uber-clone-adam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv_HcKzfl2W9FCzTUC5vuH7Ilcr3clcTk',
    appId: '1:705177585451:ios:a162d473094b7fe479276e',
    messagingSenderId: '705177585451',
    projectId: 'uber-clone-adam',
    storageBucket: 'uber-clone-adam.appspot.com',
    iosBundleId: 'com.example.uberClone',
  );
}
